Always install importlib-metadata (not only for <3.10) and provide dummy entry_points (#195)
* Always install importlib-metadata (not only for <3.10)

* Add dummy `entry_points` function

* Adding extra group parameter. Without that nomad gives and error from L87: Unexpected keyward arg 'group'.

* fix error in noamd: TypeError: entry_points() missing 1 required positional argument: '_'

---------

Co-authored-by: Rubel <rubel.mozumder@outlook.com>